// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxH6amkJdp2mJjMve99r2aKbKqReEK3GY',
    appId: '1:608224963108:web:aee05d0160dabbebb406b1',
    messagingSenderId: '608224963108',
    projectId: 'evigo-8a332',
    authDomain: 'evigo-8a332.firebaseapp.com',
    storageBucket: 'evigo-8a332.firebasestorage.app',
    measurementId: 'G-LN4Q6KML1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF524CEXFDmLue_9D6a8UuFcVP03_Njzs',
    appId: '1:608224963108:android:9da588408f126cd7b406b1',
    messagingSenderId: '608224963108',
    projectId: 'evigo-8a332',
    storageBucket: 'evigo-8a332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9W-7TivPASaFk3iKCtKqzXezu6uG_vc',
    appId: '1:608224963108:ios:35a1d23e34dbe7d5b406b1',
    messagingSenderId: '608224963108',
    projectId: 'evigo-8a332',
    storageBucket: 'evigo-8a332.firebasestorage.app',
    iosBundleId: 'com.example.nobile',
  );
}
